export const state = {
  frames: [],
  sheetBlob: null,
  gifBlob: null,
  gifUrl: null,
  index: null,
  characterPack: {
    file: null,
    blackFile: null,
    referenceFile: null,
    paletteFile: null,
    sourceUrl: null,
    sourceSize: null,
    manualCutLines: null,
    useManualCutLines: false,
    manualFrameAdjustments: {},
    lockedAnimations: [],
    job: null,
    debugReport: null,
    providerPresetId: null,
    providerPresets: [],
    repairPlan: null,
    repairActions: [],
    benchmarkGallery: {
      runs: [],
      loading: false,
      error: null,
      updatedAt: null,
    },
    preview: {
      image: null,
      inspectionImage: null,
      inspectionIndex: null,
      sourceImage: null,
      animations: null,
      animationName: null,
      frameCursor: 0,
      lastTime: 0,
      lastMoveTime: 0,
      keys: new Set(),
      direction: 'down',
      position: { x: 192, y: 166 },
      wasMoving: false,
      raf: null,
    },
  },
  scenePack: {
    job: null,
  },
  twoPointFiveD: {
    job: null,
    benchmark: null,
    operations: [],
  },
  motionSource: {
    view: 'guided',
    sourceFile: null,
    sourceMeta: null,
    sourceDescriptor: null,
    sourceEpoch: 0,
    sourceUploadOperationId: null,
    selectionMode: 'auto',
    uiOperation: null,
    activeOperation: null,
    resumableOperation: null,
    observationController: null,
    renderToken: 0,
    releaseTasks: new Map(),
    sheetFile: null,
    stripFile: null,
    manifestFile: null,
    setStripFiles: [],
    stripUrl: null,
    frameCandidates: [],
    frameSelection: [],
    framePreviewIndexUrl: null,
    previewBinding: null,
    buildBinding: null,
    artifactErrors: {
      analysis: {},
      preview: {},
      build: {},
      apply: {},
      set: {},
      setApply: {},
    },
    applyResultStale: false,
    toolStatus: null,
    reports: {
      analysis: null,
      preview: null,
      build: null,
      apply: null,
      set: null,
      setApply: null,
    },
    jobs: {
      analysis: null,
      preview: null,
      build: null,
      apply: null,
      set: null,
      setApply: null,
    },
  },
  projectPack: {
    job: null,
  },
}
