import {
  FIXED_REGION_MOTION_LAYOUT_ID,
  TOPDOWN_RPG_SOURCE_LAYOUT_ID,
} from './sourceLayoutIds.js'

export const DEFAULT_UPLOAD_SOURCE_LAYOUT = TOPDOWN_RPG_SOURCE_LAYOUT_ID
export const DEFAULT_GENERATION_PRESET = FIXED_REGION_MOTION_LAYOUT_ID
export const DEFAULT_TOPDOWN_REPAIR_PRESET = TOPDOWN_RPG_SOURCE_LAYOUT_ID
