export const TWO_POINT_FIVE_D_WORKFLOW_RELEASE_EVIDENCE_MODE = 'two_point_five_d_workflow_release_evidence_v1'

function stageStatus(status, fallback = 'not_run') {
  if (!status) return fallback
  if (status === 'pass' || status === 'done') return 'pass'
  if (status === 'warning') return 'warning'
  if (status === 'not_applicable') return 'not_applicable'
  return 'fail'
}

function artifactPresent(artifacts, key) {
  return Boolean(artifacts?.[key])
}

function item({ id, label, status, evidence = [], warnings = [], required = true }) {
  return {
    id,
    label,
    required,
    status,
    evidence,
    warnings,
  }
}

export function buildTwoPointFiveDWorkflowReleaseEvidence({
  plan,
  validationReport,
  sourceNormalization,
  materialSourceReport,
  tileMap,
  tileMapValidation,
  constraintSolverReport,
  mapEditorWorkflow,
  ldtkProjectValidation,
  ldtkWorkflowValidation,
  artifacts = {},
} = {}) {
  const hasManualSource = Boolean(sourceNormalization || materialSourceReport)
  const checklist = [
    item({
      id: 'source_normalizer',
      label: 'Manual source is normalized before material extraction',
      status: hasManualSource ? stageStatus(sourceNormalization?.status) : 'not_applicable',
      required: false,
      evidence: hasManualSource
        ? ['source_normalization_report', 'normalized_material_source_png'].filter((key) => artifactPresent(artifacts, key))
        : ['procedural_material_profile'],
      warnings: sourceNormalization?.warnings ?? [],
    }),
    item({
      id: 'material_slot_semantics',
      label: 'Material slots are separated from source layout and rendered by local composer',
      status: hasManualSource ? stageStatus(materialSourceReport?.status) : 'pass',
      evidence: [
        'material_profile',
        hasManualSource ? 'material_source_report' : null,
        hasManualSource && artifactPresent(artifacts, 'material_slot_candidates_png') ? 'material_slot_candidates_png' : null,
        hasManualSource && artifactPresent(artifacts, 'material_patches_png') ? 'material_patches_png' : null,
      ].filter(Boolean),
      warnings: materialSourceReport?.warnings ?? [],
    }),
    item({
      id: 'tileset_validation',
      label: 'Strict atlas and metadata pass local validation',
      status: stageStatus(validationReport?.status),
      evidence: ['strict_atlas_png', 'runtime_padded_atlas_png', 'validation_report', 'metadata'].filter((key) => artifactPresent(artifacts, key)),
      warnings: validationReport?.warnings ?? [],
    }),
    item({
      id: 'constraint_map_solver',
      label: 'Map is generated by guarded constraints before export',
      status: constraintSolverReport ? stageStatus(constraintSolverReport.status) : 'warning',
      evidence: ['constraint_solver_report', 'tile_map', 'tile_map_validation'].filter((key) => artifactPresent(artifacts, key)),
      warnings: constraintSolverReport ? [] : ['seeded_solver_fallback_used'],
    }),
    item({
      id: 'map_editor_workflow',
      label: 'Map editor operations are applied through the rule-safe workflow',
      status: stageStatus(mapEditorWorkflow?.status),
      evidence: ['map_editor_workflow', 'map_editor_preview_png'].filter((key) => artifactPresent(artifacts, key)),
      warnings: mapEditorWorkflow?.operations?.length ? [] : ['no_editor_operations_applied'],
    }),
    item({
      id: 'rule_map_validation',
      label: 'Edited map passes shared-edge rule validation',
      status: stageStatus(tileMapValidation?.status),
      evidence: ['tile_map_validation', 'rule_map_preview_png'].filter((key) => artifactPresent(artifacts, key)),
      warnings: tileMapValidation?.warnings ?? [],
    }),
    item({
      id: 'ldtk_import_readiness',
      label: 'LDtk project, TerrainMasks, and auto-layer rules are statically import-ready',
      status: stageStatus(ldtkWorkflowValidation?.status ?? ldtkProjectValidation?.status),
      evidence: ['ldtk_project', 'ldtk_auto_layer_rules', 'ldtk_project_validation', 'ldtk_workflow_validation'].filter((key) => artifactPresent(artifacts, key)),
      warnings: ldtkWorkflowValidation?.warnings ?? [],
    }),
    item({
      id: 'tiled_export',
      label: 'Tiled JSON and TSX exports are present with 2.5D metadata',
      status: artifactPresent(artifacts, 'tiled_json') && artifactPresent(artifacts, 'tiled_tsx') ? 'pass' : 'fail',
      evidence: ['tiled_json', 'tiled_tsx'].filter((key) => artifactPresent(artifacts, key)),
    }),
  ]

  const requiredItems = checklist.filter((entry) => entry.required !== false)
  const failedItems = requiredItems.filter((entry) => entry.status === 'fail' || entry.status === 'not_run')
  const warningItems = checklist.filter((entry) => entry.status === 'warning' || entry.warnings.length)
  const status = failedItems.length ? 'fail' : warningItems.length ? 'warning' : 'pass'

  return {
    schema_version: 1,
    mode: TWO_POINT_FIVE_D_WORKFLOW_RELEASE_EVIDENCE_MODE,
    status,
    release_ready: status !== 'fail',
    contract_id: plan?.contract_id ?? null,
    rule_profile_id: plan?.rule_profile?.id ?? null,
    map: tileMap
      ? {
          width: tileMap.width,
          height: tileMap.height,
          arrangement: tileMap.arrangement,
          validation_status: tileMapValidation?.status ?? 'not_run',
        }
      : null,
    editor: mapEditorWorkflow
      ? {
          status: mapEditorWorkflow.status,
          operation_count: mapEditorWorkflow.operations.length,
          changed_cell_count: mapEditorWorkflow.changed_cell_count,
        }
      : null,
    ldtk: {
      project_validation_status: ldtkProjectValidation?.status ?? 'not_run',
      workflow_validation_status: ldtkWorkflowValidation?.status ?? 'not_run',
      auto_layer_rule_count: ldtkProjectValidation?.metrics?.auto_layer_rule_count ?? null,
      import_readiness_claim: ldtkWorkflowValidation?.claim_boundary ?? null,
    },
    checklist,
    summary: {
      required_count: requiredItems.length,
      failed_count: failedItems.length,
      warning_count: warningItems.length,
      artifact_count: Object.keys(artifacts).length,
      manual_source_mode: hasManualSource,
    },
    claim_boundary: 'End-to-end local workflow evidence for browser/API-driven 2.5D tileset builds; external editor launch and live provider generation are outside this artifact.',
  }
}

export function renderTwoPointFiveDWorkflowReleaseEvidenceMarkdown(evidence) {
  const rows = (evidence?.checklist ?? [])
    .map((entry) => `| ${entry.id} | ${entry.status} | ${(entry.evidence ?? []).join(', ') || '-'} | ${(entry.warnings ?? []).join(', ') || '-'} |`)
    .join('\n')
  return [
    '# 2.5D Workflow Release Evidence',
    '',
    `Status: ${evidence?.status ?? 'unknown'}`,
    `Release ready: ${evidence?.release_ready ? 'yes' : 'no'}`,
    `Contract: ${evidence?.contract_id ?? '-'}`,
    `Rule profile: ${evidence?.rule_profile_id ?? '-'}`,
    '',
    '| Check | Status | Evidence | Warnings |',
    '|---|---:|---|---|',
    rows,
    '',
    `Claim boundary: ${evidence?.claim_boundary ?? '-'}`,
    '',
  ].join('\n')
}
